"""Shared data models for Optimizer modules.

All modules communicate using these dataclasses. Lock these in Hour 0 of development
before implementation begins. Changes to these schemas affect all modules.

Owner: All team members (consensus-driven)
"""

from dataclasses import dataclass, field
from typing import Optional


@dataclass
class WorkloadResult:
    """
    Result of running a single workload command.

    Returned by profiler.runner.run_workload() and profiler.runner.benchmark_workload().
    Used by verifier to benchmark candidates.
    """

    runtime_ms: float
    """Elapsed time in milliseconds."""

    exit_code: int
    """Process exit code (0 = success, non-zero = failure, -1 = system error)."""

    command: str
    """The command that was executed."""

    output: str
    """Captured stdout + stderr combined."""

    timestamp: str
    """ISO 8601 timestamp when the run started."""


@dataclass
class Hotspot:
    """
    A performance bottleneck identified by profiling.

    Produced by profiler.profiler.identify_hotspots().
    Consumed by agent to generate optimization candidates.
    """

    function: str
    """Simple function name (e.g., 'generate_feed')."""

    qualified_name: str
    """Fully qualified name (e.g., 'services.recommendations.generate_feed')."""

    file: str
    """Path to the file containing this function."""

    line: int
    """Line number where function is defined."""

    calls: int
    """Number of times this function was called during profiling."""

    self_time: float
    """Time spent in this function's own code (seconds), excluding callees."""

    cumulative_time: float
    """Total time spent in this function and everything it calls (seconds)."""

    runtime_percent: float
    """Percentage of total runtime spent in this function (0-100)."""

    dependencies: list[str] = field(default_factory=list)
    """Qualified names of functions this hotspot calls."""

    related_files: list[str] = field(default_factory=list)
    """Files involved in the call chain from this hotspot."""


@dataclass
class CandidateOptimization:
    """
    A proposed optimization with benchmark results.

    Produced by agent.candidate_generator.generate_candidates().
    Passed to verifier for testing and benchmarking.
    Updated by verifier with test/benchmark results.
    """

    candidate_id: str
    """Unique identifier (e.g., 'candidate_a', 'candidate_b')."""

    strategy: str
    """Human-readable optimization strategy (e.g., 'batch user retrieval')."""

    files_changed: list[str]
    """Paths to files modified by this candidate (1-3 files)."""

    # Generated by verifier
    tests_passed: bool = False
    """True if all tests passed after applying this candidate."""

    test_output: Optional[str] = None
    """Captured output from running test suite."""

    benchmark_before_ms: Optional[float] = None
    """Baseline execution time before applying candidate (ms)."""

    benchmark_after_ms: Optional[float] = None
    """Execution time after applying candidate (ms)."""

    benchmark_failed: bool = False
    """True if candidate process exited with non-zero code during benchmark."""

    speedup: Optional[float] = None
    """Speedup ratio: benchmark_before_ms / benchmark_after_ms."""

    accepted: bool = False
    """True if this candidate was selected and applied (only one per pass)."""

    explanation: Optional[str] = None
    """Agent's explanation of the optimization strategy."""


@dataclass
class OptimizationPass:
    """
    One iteration of the optimization loop (profile → optimize → benchmark → apply).

    Produced by main optimization loop.
    Used for reporting and multi-pass tracking.
    """

    pass_number: int
    """Pass number (1-indexed)."""

    hotspot: Hotspot
    """The bottleneck targeted in this pass."""

    candidates: list[CandidateOptimization]
    """All candidate optimizations considered."""

    selected_candidate: Optional[CandidateOptimization] = None
    """The candidate that was accepted and applied (if any)."""

    speedup: Optional[float] = None
    """Overall speedup from this pass (if candidate was accepted)."""

    status: str = "pending"
    """Status: 'pending', 'in_progress', 'completed', 'failed'."""


# Type hints for common return values
WorkloadDict = dict
"""Plain dict matching WorkloadResult fields (used for dict-based interchange)."""

HotspotDict = dict
"""Plain dict matching Hotspot fields."""

CandidateDict = dict
"""Plain dict matching CandidateOptimization fields."""
